config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  resources :patients

  resources :exams

  resources :users

  root 'home#index'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :exams

  has_and_belongs_to_many :users

  # search
  def self.search(search)
    where("name ILIKE ? OR last_name ILIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    if user_signed_in?
      if params[:search]
        # @patients = Patient.search(params[:search]).where(:users => current_user).order('last_name ASC')
        @patients = current_user.patients.search(params[:search]).order('last_name ASC')
      else
        @patients = Patient.all.order('last_name ASC')
      end
    else
      flash[:alert] = 'Devi essere registrato e accedere al tuo profilo per poter cercare i pazienti'
      redirect_to(:controller => 'home', :action => 'index')
    end
  end

  def show
    @patient = Patient.find(params[:id])
    @exams = @patient.exams.order('created_at ASC')
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      flash[:notice] = 'Paziente salvato correttamente'
      redirect_to patient_path(@patient)
    end
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    if @patient.update_attributes(patient_params)
      flash[:notice] = "Dati paziente aggiornati"
      redirect_to patient_path(@patient)
    end
  end

  private
  def patient_params
    params.require(:patient).permit(:name, :last_name, :birth_date, :familiarity, :smoker, :last_hygiene, :anamnesis, :allergies, :intollerances, :drugs)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/edit.html.erb
<div class="content">
<h1><%= @patient.name + ' ' + @patient.last_name%></h1>

  <%= semantic_form_for @patient do |f| %>
    <%= f.inputs %>
    <%= f.actions %>
  <% end %>

</div>

app/views/patients/index.html.erb
<div class="content">
  <h1>Pazienti</h1>
  <% if @patients.present? %>
  <table class="table">
    <tr>
      <th>Nome e Cognome</th>
      <th>Età</th>
      <th>Ultima visita</th>
    </tr>

    <% @patients.each do |p| %>
    <tr>
      <td><%= link_to (p.name + ' ' + p.last_name), patient_path(p) %></td>
      <td><%= p.birth_date%></td>
      <td><%= p.last_hygiene%></td>
    </tr>
    <% end %>

  </table>
  <% else %>
    <p>Non ci sono pazienti con questo nome o cognome nel tuo archivio</p>
  <% end %>

</div>

app/views/patients/new.html.erb
<div class="content">
  <h1>Nuovo paziente</h1>
  <p>Inserisci i dati del paziente: potrai comunque modificarli in un secondo momento</p>

  <%= semantic_form_for @patient do |f| %>
    <%= f.inputs %>
    <%= f.actions %>
  <% end %>

</div>

app/views/patients/show.html.erb
<div class="content">
    <h1><%= @patient.name + ' ' + @patient.last_name%></h1>
  <table class="table patient">
    <tr>
      <th>Data di nascita</th>
      <td><%= @patient.birth_date%></td>
    </tr>
    <tr>
      <th>Familiarità</th>
      <td><%= @patient.familiarity%></td>
    </tr>
    <tr>
      <th>Fumatore</th>
      <td><%= @patient.smoker%></td>
    </tr>
    <tr>
      <th>Ultima igiene</th>
      <td><%= @patient.last_hygiene%></td>
    </tr>
    <tr>
      <th>Ananmesi</th>
      <td><%= @patient.anamnesis%></td>
    </tr>
    <tr>
      <th>Allergie</th>
      <td><%= @patient.allergies%></td>
    </tr>
    <tr>
      <th>Intolleranze</th>
      <td><%= @patient.intollerances%></td>
    </tr>
    <tr>
      <th>Farmaci</th>
      <td><%= @patient.drugs%></td>
    </tr>
  </table>
  <button class="btn btn-info center-block"><%= link_to 'modifica dati paziente', edit_patient_path(@patient)%></button>
<hr />
  <h2>Esami precedenti</h2>
  <% if @patient.exams.present? %>
  <table class="table table-striped">
    <tr>
      <th class="exams-date">Data esame</th>
      <th class="exams-type">Tipo</th>
      <th class="exams-notes">Note</th>
    </tr>
    <% @exams.each do |e| %>
      <tr>
        <td><%= link_to e.created_at.to_date, exam_path(e) %></td>
        <td><%= e.exam_type %></td>
        <td><%= e.notes %></td>
      </tr>
    <% end %>
  </table>
  <% else %>
    <h5>Questo paziente non ha esami registrati a suo nome</h5>
  <% end %>
  <button class="btn btn-info center-block"><%= link_to 'Nuovo esame', new_exam_path(:patient_id => @patient)%></button>
</div>