config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  resources :patients

  resources :exams

  resources :users

  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cartellaparodontale</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://www.google.com/jsapi" %>
  <%= csrf_meta_tags %>
</head>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Cartella Parodontale', root_path, :class => 'navbar-brand' %>
      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Cerca pazienti", root_path%></li>
        <li><%= link_to "Nuovo paziente", new_patient_path%></li>
      </ul>
      <% end %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <% if current_user.present? %>
            <li><%= link_to 'Profilo', user_path(current_user)%></li>
          <% else %>
            <li><a>Role: not yet assigned</a></li>
          <% end %>

          <li role="separator" class="divider"></li>
          <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>

        </ul>
        <% else %>
        <li><%= link_to 'Accedi', new_user_session_path()%></li>
      </li>
      <% end %>
    </ul>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<body>


<div class="messages">
  <% if notice.present? %>
    <div class="notice">
      <p><%= notice %></p>
      <p class="small-text"> Clicca per nascondere</p>
    </div>
  <% end %>

  <% if alert.present? %>
    <div class="alert">
      <p><%= alert %></p>
      <p class="small-text"> Clicca per nascondere</p>
    </div>
  <% end %>
</div>

<%= yield %>

</body>

<footer>
  <h3>La Cartella Parodontale</h3>
  <p>Un progetto realizzato da Giulio, Magda e Diego</p>
</footer>
</html>